//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LH.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings_pt_BR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings_pt_BR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LH.Resources.Strings_pt-BR", typeof(Strings_pt_BR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modelo de log. Use marcadores entre &lt; e &gt;.
        ///Exemplo: &quot;&lt;dd/MM/yyyy HH:mm:ss.fff&gt; [&lt;level&gt;] (&lt;stack&gt;) &lt;message&gt; | &lt;obs&gt;&quot;.
        /// </summary>
        internal static string FormatLogOutput {
            get {
                return ResourceManager.GetString("FormatLogOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nível hierárquico máximo a ser registrado na pilha de métodos (índice final). Exemplo: 5.
        /// </summary>
        internal static string LevelStack {
            get {
                return ResourceManager.GetString("LevelStack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nível mínimo a ser registrado no console de log.
        ///Exemplo: Se definido como 2, os logs TRACE e DEBUG não serão registrados.
        ///Digite um número negativo para evitar o registro de logs..
        /// </summary>
        internal static string LogLevelConsole {
            get {
                return ResourceManager.GetString("LogLevelConsole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nível mínimo a ser registrado no arquivo de log.
        ///Exemplo: Se definido como 2, os logs TRACE e DEBUG não serão registrados.
        ///Digite um número negativo para evitar o registro de logs..
        /// </summary>
        internal static string LogLevelFile {
            get {
                return ResourceManager.GetString("LogLevelFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nível mínimo a ser registrado no log de rastreamento.
        ///Exemplo: Se definido como 2, os logs TRACE e DEBUG não serão registrados.
        ///Digite um número negativo para evitar o registro de logs..
        /// </summary>
        internal static string LogLevelTrace {
            get {
                return ResourceManager.GetString("LogLevelTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local onde o arquivo de log será armazenado.
        ///(Especifique um local ou nome de arquivo diferente para usar arquivos de log diferentes)..
        /// </summary>
        internal static string LogPathFile {
            get {
                return ResourceManager.GetString("LogPathFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de dias após os quais o arquivo de log deve ser considerado desatualizado e será excluído. O padrão é 3 dias..
        /// </summary>
        internal static string LogValidity {
            get {
                return ResourceManager.GetString("LogValidity", resourceCulture);
            }
        }
    }
}
