//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LH.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LH.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log template. Use placeholders between &lt; and &gt;.
        ///Example: &quot;&lt;dd/MM/yyyy HH:mm:ss.fff&gt; [&lt;level&gt;] (&lt;stack&gt;) &lt;message&gt; | &lt;obs&gt;&quot;.
        /// </summary>
        internal static string FormatLogOutput {
            get {
                return ResourceManager.GetString("FormatLogOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum hierarchical level to be logged in the method stack (final index). Example: 5.
        /// </summary>
        internal static string LevelStack {
            get {
                return ResourceManager.GetString("LevelStack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum level to be logged in the log console.
        ///Example: If set to 2, TRACE and DEBUG logs will not be logged.
        ///Enter a negative number to avoid recording logs..
        /// </summary>
        internal static string LogLevelConsole {
            get {
                return ResourceManager.GetString("LogLevelConsole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum level to be logged in the log file.
        ///Example: If set to 2, TRACE and DEBUG logs will not be logged.
        ///Enter a negative number to avoid recording logs..
        /// </summary>
        internal static string LogLevelFile {
            get {
                return ResourceManager.GetString("LogLevelFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum level to be logged in the log trace.
        ///Example: If set to 2, TRACE and DEBUG logs will not be logged.
        ///Enter a negative number to avoid recording logs..
        /// </summary>
        internal static string LogLevelTrace {
            get {
                return ResourceManager.GetString("LogLevelTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location where the log file will be stored.
        ///(Specify a different location or filename to use different log files)..
        /// </summary>
        internal static string LogPathFile {
            get {
                return ResourceManager.GetString("LogPathFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of days after which the log file should be considered outdated and will be deleted. Default is 3 days..
        /// </summary>
        internal static string LogValidity {
            get {
                return ResourceManager.GetString("LogValidity", resourceCulture);
            }
        }
    }
}
